cloudflare:
  account: ""
  tunnelName: ""
  tunnelId: ""
  secret: ""
  ingress:
    - hostname: warp.valkhium.xyz
      service: http://vlk-warp.vlk-gateway.svc.cluster.local:80
    - hostname: atlas.valkhium.xyz
      service: http://vlk-atlas.vlk-worker.svc.cluster.local:80

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: 2025.5.0

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
